### ISSUE TITLE
9 - Checklist

### ISSUE THREAD

**Issue by omegabytes** [omegabytes/csc648group06#20]
- [x] 	Team decided on basic means of communications
- [x]  Team found a time slot to meet  outside of the class
- [x]  CTO chosen and working out well so far
- [x]  Github master chosen
- [x]  Team ready and able to use the chosen framework
- [x]  Skills of each team member defined and known to all
- [x]  Team lead ensured that all team members read the  final M1 and agree/understand it before submission
